#!/bin/bash

qmake

##########################################
# Test release version
##########################################
make release

n_errors=0

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels"
  ((++n_errors))
fi

#####################
# Test exit states
#####################

./main > /dev/null
state_zero=`echo $?`

./main 1 > /dev/null
state_one=`echo $?`

./main nonsense > /dev/null
state_nonsense=`echo $?`

./main 1 2 > /dev/null
state_one_two=`echo $?`

if [[ ! $state_zero -eq 1 ]]; then
  echo "Incorrect: './is_perfect' should return exit state 1, as one argument is needed"
  ((++n_errors))
fi

if [[ ! $state_one -eq 0 ]]; then
  echo "Incorrect: './is_perfect 1' should return exit state 0, as 1 is an integer"
  ((++n_errors))
fi

if [[ ! $state_nonsense -eq 1 ]]; then
  echo "Incorrect: './is_perfect nonsense' should return exit state 1, as 'nonsense' is no integer"
  ((++n_errors))
fi

if [[ ! $state_one_two -eq 1 ]]; then
  echo "Incorrect: './is_perfect 1 2' should return exit state 1, as there are two arguments"
  ((++n_errors))
fi

#####################
# Test output
#####################

# Create expected result
echo "false" > expected_0.txt
echo "false" > expected_1.txt
echo "false" > expected_2.txt
echo "true" > expected_6.txt
echo "false" > expected_12.txt
echo "true" > expected_28.txt

# Create the actual result
./main 0 > created_0.txt
./main 1 > created_1.txt
./main 2 > created_2.txt
./main 6 > created_6.txt
./main 12 > created_12.txt
./main 28 > created_28.txt

# Compare results
if ! cmp --silent created_0.txt expected_0.txt; then
  echo "Incorrect: './is_perfect 0' should literally display 'false', followed by a newline"
  ((++n_errors))
fi

if ! cmp --silent created_1.txt expected_1.txt; then
  echo "Incorrect: './is_perfect 1' should literally display 'false', followed by a newline"
  ((++n_errors))
fi

if ! cmp --silent created_2.txt expected_2.txt; then
  echo "Incorrect: './is_perfect 2' should literally display 'false', followed by a newline"
  ((++n_errors))
fi

if ! cmp --silent created_6.txt expected_6.txt; then
  echo "Incorrect: './is_perfect 6' should literally display 'false', followed by a newline"
  ((++n_errors))
fi

if ! cmp --silent created_12.txt expected_12.txt; then
  echo "Incorrect: './is_perfect 12' should literally display 'false', followed by a newline"
  ((++n_errors))
fi

if ! cmp --silent created_28.txt expected_28.txt; then
  echo "Incorrect: './is_perfect 28' should literally display 'true', followed by a newline"
  ((++n_errors))
fi

rm expected_*.txt
rm created_*.txt

#####################
# Test misc
#####################

# Avoid endls
n=`cat main.cpp | egrep "endl" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: C++ Core Guidelines: SL.io.50: Avoid endl"
  ((++n_errors))
fi

# Catch exceptions by reference
n=`cat main.cpp | egrep "invalid_argument\s*\w*\s*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: C++ Core Guidelines: E.15: Catch exceptions from a hierarchy by reference"
  ((++n_errors))
fi

n=`cat main.cpp | egrep "out_of_range\s*\w*\s*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: C++ Core Guidelines: E.15: Catch exceptions from a hierarchy by reference"
  ((++n_errors))
fi

n=`cat main.cpp | egrep "exception\s*\w*\s*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: C++ Core Guidelines: E.15: Catch exceptions from a hierarchy by reference"
  ((++n_errors))
fi

# Exceptions should be const
n=`cat main.cpp | egrep "\(\w*(std::)?invalid_argument" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: C++ Core Guidelines: Con.4: Use const to define objects with values that do not change after construction"
  ((++n_errors))
fi

n=`cat main.cpp | egrep "\(\w*(std::)?out_of_range" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: C++ Core Guidelines: Con.4: Use const to define objects with values that do not change after construction"
  ((++n_errors))
fi

n=`cat main.cpp | egrep "\(\w*(std::)?exception" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: C++ Core Guidelines: Con.4: Use const to define objects with values that do not change after construction"
  ((++n_errors))
fi

# Do not use ellipsis
n=`cat main.cpp | egrep "\(\w*\.\.\.\w*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Incorrect: do not use ellipsis"
  ((++n_errors))
fi

##########################################
# Test debug version
##########################################
make debug
./main

#####################
# Test code coverage
#####################

n=`gcov-7 -i -n -o debug main.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
if [ ! "$n" -eq "1" ]; then
  echo "Incorrect: must have 100% code coverage. Current code coverage:"
  gcov-7 -i -n -o debug main.cpp | head -n 2 | tail -n 1
  ((++n_errors))
fi

exit $n_errors
