#!/bin/bash

n_errors=0

for folder in `ls -d */`; do
  cd $folder
  if [ -f test ]; then 
    cp ../shared/test_tests .
    cp ../shared/main.pro .
    ./test_tests > /dev/null
    test_exit_state=`echo $?`
    if [[ ! $test_exit_state -eq 0 ]]; then
      echo "Incorrect: tests in folder '"$folder"' fail"
      ((++n_errors))
    fi

    rm test_tests
    rm main.pro
  fi 
  cd ..
done

exit $n_errors