#!/bin/bash

# GCC 5, GCC 7
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -qq

# Codecov
sudo pip install codecov

# OCLint
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/install_oclint
chmod +x install_oclint 
./install_oclint

# GCC5 
sudo apt-get install -qq g++-5
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
# GCC 7
# - sudo apt-get install -qq g++-7
# - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
# - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
# cppcheck
sudo apt-get install -qq cppcheck

# OCLint
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/do_oclint
chmod +x do_oclint

# Codecov
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/get_code_cov
chmod +x get_code_cov

# main.pro file
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/main.pro
