#!/bin/bash

qmake > /dev/null

##########################################
# Test release version
##########################################
make release > /dev/null

n_errors=0

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels in release mode"
  ((++n_errors))
fi

./main

##########################################
# Test debug version
##########################################
make debug > /dev/null

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels in debug mode"
  ((++n_errors))
fi

./main

#####################
# Test code coverage
#####################

n=`gcov -n -o debug main.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
if [ ! "$n" -eq "1" ]; then
  echo "Incorrect: must have 100% code coverage. Current code coverage:"
  gcov -n -o debug main.cpp | head -n 2 | tail -n 1
  ((++n_errors))
fi

exit $n_errors