#!/bin/bash

qmake > /dev/null

##########################################
# Test release version
##########################################
make release > /dev/null

n_errors=0

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels"
  ((++n_errors))
fi

#####################
# Test exit states
#####################

./main > /dev/null
state_zero=`echo $?`

./main 1 > /dev/null
state_one=`echo $?`

./main nonsense > /dev/null
state_nonsense=`echo $?`

./main 1 2 > /dev/null
state_one_two=`echo $?`

if [[ ! $state_zero -eq 1 ]]; then
  echo "Incorrect: './is_prime' should return an exit state of 1, as there are too few arguments"
  ((++n_errors))
fi

if [[ ! $state_one -eq 0 ]]; then
  echo "Incorrect: './is_prime 1' should return an exit state of 0"
  ((++n_errors))
fi

if [[ ! $state_nonsense -eq 1 ]]; then
  echo "Incorrect: './is_prime nonsense' should return an exit state of 1, as 'nonsense' is no integer"
  ((++n_errors))
fi

if [[ ! $state_one_two -eq 1 ]]; then
  echo "Incorrect: './is_prime 1 2' should return an exit state of 1, as there are too many arguments"
  ((++n_errors))
fi

#####################
# Test output
#####################

# Create expected result
echo "false" > expected_0.txt
echo "false" > expected_1.txt
echo "true"  > expected_2.txt
echo "true"  > expected_3.txt
echo "false" > expected_4.txt
echo "true"  > expected_5.txt

# Create the actual result
./main 0 > created_0.txt
./main 1 > created_1.txt
./main 2 > created_2.txt
./main 3 > created_3.txt
./main 4 > created_4.txt
./main 5 > created_5.txt

# Compare results
if ! cmp --silent created_0.txt expected_0.txt; then
  echo "Incorrect: './is_prime 0' should display 'false'"
  ((++n_errors))
fi

if ! cmp --silent created_1.txt expected_1.txt; then
  echo "Incorrect: './is_prime 1' should display 'false'"
  ((++n_errors))
fi

if ! cmp --silent created_2.txt expected_2.txt; then
  echo "Incorrect: './is_prime 2' should display 'true'"
  ((++n_errors))
fi

if ! cmp --silent created_3.txt expected_3.txt; then
  echo "Incorrect: './is_prime 3' should display 'true'"
  ((++n_errors))
fi

if ! cmp --silent created_4.txt expected_4.txt; then
  echo "Incorrect: './is_prime 4' should display 'false'"
  ((++n_errors))
fi

if ! cmp --silent created_5.txt expected_5.txt; then
  echo "Incorrect: './is_prime 5' should display 'true'"
  ((++n_errors))
fi

rm expected_*.txt
rm created_*.txt

##########################################
# C++ guidelines
##########################################

./check_cpp_core_guidelines
state_core_guidelines=`echo $?`

if [[ ! $state_core_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_cpp_core_guidelines' already does so 
  ((++n_errors))
fi

./check_course_guidelines
state_course_guidelines=`echo $?`

if [[ ! $state_course_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_course_guidelines' already does so 
  ((++n_errors))
fi

./check_doc
state_doc=`echo $?`

if [[ ! $state_doc -eq 0 ]]; then
  # No need to be verbose here, 'check_doc' already does so 
  ((++n_errors))
fi

##########################################
# Test debug version
##########################################
make debug > /dev/null
./main

#####################
# Test code coverage
#####################

n=`gcov -n -o debug main.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
if [ ! "$n" -eq "1" ]; then
  echo "Incorrect: must have 100% code coverage. Current code coverage:"
  gcov -n -o debug main.cpp | head -n 2 | tail -n 1
  ((++n_errors))
fi

exit $n_errors
