#!/bin/bash

qmake > /dev/null

##########################################
# Test release version
##########################################
make release > /dev/null

n_errors=0

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels"
  ((++n_errors))
fi

#####################
# Test exit states
#####################

./main > /dev/null
state_zero=`echo $?`

./main hello > /dev/null
state_one=`echo $?`

./main hello i_am_ignored > /dev/null
state_two=`echo $?`


if [[ ! $state_zero -eq 0 ]]; then
  echo "Incorrect: call without arguments must result in an exit state of 0"
  ((++n_errors))
fi

if [[ ! $state_one -eq 0 ]]; then
  echo "Incorrect: call with one argument must result in an exit state of 0"
  ((++n_errors))
fi

if [[ ! $state_two -eq 0 ]]; then
  echo "Incorrect: call with two arguments must result in an exit state of 0"
  ((++n_errors))
fi

#####################
# Test output
#####################

# Create expected result
echo "Hello" > expected_0.txt
echo "Hello world" > expected_1.txt
echo "Hello world" > expected_2.txt

# Create the actual result
./main > created_0.txt
./main world > created_1.txt
./main world i_am_ignored > created_2.txt

# Compare
if ! cmp --silent created_0.txt expected_0.txt; then
  echo "Incorrect: './hello_cli' literally say 'Hello'"
  ((++n_errors))
fi

# Compare the two
if ! cmp --silent created_1.txt expected_1.txt; then
  echo "Incorrect: './hello_cli world' literally say 'Hello world'"
  ((++n_errors))
fi

# Compare the two
if ! cmp --silent created_2.txt expected_2.txt; then
  echo "Incorrect: './hello_cli world i_am_ignored' literally say 'Hello world' and ignore the second argument"
  ((++n_errors))
fi

rm expected_*.txt
rm created_*.txt

##########################################
# C++ guidelines
##########################################

./check_cpp_core_guidelines
state_core_guidelines=`echo $?`

if [[ ! $state_core_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_cpp_core_guidelines' already does so 
  ((++n_errors))
fi

./check_course_guidelines
state_course_guidelines=`echo $?`

if [[ ! $state_course_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_course_guidelines' already does so 
  ((++n_errors))
fi

./check_doc
state_doc=`echo $?`

if [[ ! $state_doc -eq 0 ]]; then
  # No need to be verbose here, 'check_doc' already does so 
  ((++n_errors))
fi

##########################################
# Test debug version
##########################################
make debug > /dev/null

./main
./main hello
./main hello i_am_ignored

#####################
# Test code coverage
#####################

n=`gcov -n -o debug main.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
if [ ! "$n" -eq "1" ]; then
  echo "Error: must have 100% code coverage. Current code coverage:"
  gcov -n -o debug main.cpp | head -n 2 | tail -n 1
  ((++n_errors))
fi

exit $n_errors
