#!/bin/bash

qmake > /dev/null

##########################################
# Test release version
##########################################
make release > /dev/null

n_errors=0

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels"
  ((++n_errors))
fi

# Create expected result
echo "Hello world" > expected.txt

# Create the actual result
./main > created.txt

# Compare the two
if ! cmp --silent created.txt expected.txt; then
  echo "Incorrect: output should literally be 'Hello world'"
  ((++n_errors))
fi

##########################################
# C++ guidelines
##########################################

./check_cpp_core_guidelines
state_core_guidelines=`echo $?`

if [[ ! $state_core_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_cpp_core_guidelines' already does so 
  ((++n_errors))
fi

./check_course_guidelines
state_course_guidelines=`echo $?`

if [[ ! $state_course_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_course_guidelines' already does so 
  ((++n_errors))
fi

##########################################
# Test debug version
##########################################
make debug > /dev/null
./main

#####################
# Test code coverage
#####################

n=`gcov -n -o debug main.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
if [ ! "$n" -eq "1" ]; then
  echo "Incorrect: must have 100% code coverage. Current code coverage:"
  gcov -n -o debug main.cpp | head -n 2 | tail -n 1
  ((++n_errors))
fi

exit $n_errors
