#!/bin/bash

# Tests the test script.
for filename in `ls main_*.cpp`; do

  # Remove main iff present
  if [[ -f main ]]; then rm main; fi

  cp $filename main.cpp
  ./build &> /dev/null
  ./test &> /dev/null
  exit_code=`echo $?`
  if [[ ! $exit_code -eq 1 ]]; then
    echo "Incorrect: file with name '"$filename" ' should fail"
    exit 1
  fi
  rm main.cpp
done

echo "Correct"
