#!/bin/bash

# From https://stackoverflow.com/a/17809718

# Start a new process with your app in the background.
./main &

pid=$!

echo "PID: "$pid

# Let the program start
sleep 3

# Send SIGTER to process
kill $pid