#!/bin/bash


qmake > /dev/null

##########################################
# Test release version
##########################################
make release > /dev/null

n_errors=0

if [[ ! -f main ]]; then 
  make release
  echo "Incorrect: code does not compile cleanly with high warning levels in release mode"
  exit 1
fi

##########################################
# Test debug version
##########################################
make debug > /dev/null

if [[ ! -f main ]]; then 
  make debug
  echo "Incorrect: code does not compile cleanly with high warning levels in debug mode"
  exit 1
fi

##########################################
# C++ guidelines
##########################################

./check_cpp_core_guidelines
state_core_guidelines=`echo $?`

if [[ ! $state_core_guidelines -eq 0 ]]; then
  ((++n_errors))
fi

./check_course_guidelines
state_course_guidelines=`echo $?`

if [[ ! $state_course_guidelines -eq 0 ]]; then
  ((++n_errors))
fi

./check_doc
state_doc=`echo $?`

if [[ ! $state_doc -eq 0 ]]; then
  ((++n_errors))
fi

#####################
# Test code coverage
#####################

# Start and kill program
./main &
pid=$!
sleep 3
kill $pid

if [[ 1 -eq 2 ]]; then
  n=`gcov -n -o debug *.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
  if [ ! "$n" -eq "1" ]; then
    echo "Incorrect: must have 100% code coverage. Current code coverage:"
    gcov -n -o debug *.cpp | head -n 2 | tail -n 1
    ((++n_errors))
  fi
fi

exit $n_errors
