#!/bin/bash

qmake > /dev/null

##########################################
# Test release version
##########################################
make release > /dev/null

n_errors=0

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels"
  ((++n_errors))
fi

#####################
# Test exit states
#####################

./main > /dev/null
state_zero=`echo $?`

./main true > /dev/null
state_true=`echo $?`

./main false > /dev/null
state_false=`echo $?`

./main nonsense > /dev/null
state_nonsense=`echo $?`

./main true true > /dev/null
state_true_true=`echo $?`

if [[ ! $state_zero -eq 1 ]]; then
  echo "Incorrect: './bool_to_coin' must return an exit state of 1, as there are too few arguments"
  ((++n_errors))
fi

if [[ ! $state_true -eq 0 ]]; then
  echo "Incorrect: './bool_to_coin true' must return an exit state of 0"
  ((++n_errors))
fi

if [[ ! $state_false -eq 0 ]]; then
  echo "Incorrect: './bool_to_coin false' must return an exit state of 0"
  ((++n_errors))
fi

if [[ ! $state_nonsense -eq 1 ]]; then
  echo "Incorrect: './bool_to_coin nonsense' must return an exit state of 1, as 'nonsense' is not a boolean"
  ((++n_errors))
fi

if [[ ! $state_true_true -eq 1 ]]; then
  echo "Incorrect: './bool_to_coin true true' must return an exit state of 1, as there are too many arguments"
  ((++n_errors))
fi

#####################
# Test output
#####################

# Create expected result
echo "heads" > expected_true.txt
echo "tails" > expected_false.txt

# Create the actual result
./main true > created_true.txt
./main false > created_false.txt

# Compare results
if ! cmp --silent created_true.txt expected_true.txt; then
  echo "Incorrect: './bool_to_coin true' should literally display 'heads', followed by a newline"
  ((++n_errors))
fi

if ! cmp --silent created_false.txt expected_false.txt; then
  echo "Incorrect: './bool_to_coin true' should literally display 'tails', followed by a newline"
  ((++n_errors))
fi

rm expected_*.txt
rm created_*.txt

##########################################
# C++ guidelines
##########################################

./check_cpp_core_guidelines
state_core_guidelines=`echo $?`

if [[ ! $state_core_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_cpp_core_guidelines' already does so 
  ((++n_errors))
fi

./check_course_guidelines
state_course_guidelines=`echo $?`

if [[ ! $state_course_guidelines -eq 0 ]]; then
  # No need to be verbose here, 'check_course_guidelines' already does so 
  ((++n_errors))
fi

./check_doc
state_doc=`echo $?`

if [[ ! $state_doc -eq 0 ]]; then
  # No need to be verbose here, 'check_doc' already does so 
  ((++n_errors))
fi

##########################################
# Test debug version
##########################################
make debug > /dev/null
./main

#####################
# Test code coverage
#####################

n=`gcov -n -o debug *.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
if [ ! "$n" -eq "1" ]; then
  echo "Incorrect: must have 100% code coverage. Current code coverage:"
  gcov -n -o debug *.cpp | head -n 2 | tail -n 1
  ((++n_errors))
fi

exit $n_errors
