#!/bin/bash

qmake

##########################################
# Test release version
##########################################
make release

if [[ ! -f main ]]; then 
  echo "Incorrect: code does not compile cleanly with high warning levels"
  exit 1
fi

#####################
# Test exit states
#####################

./main > /dev/null
state_zero=`echo $?`

./main 1 > /dev/null
state_one=`echo $?`

./main nonsense > /dev/null
state_nonsense=`echo $?`

./main 1 2 > /dev/null
state_one_two=`echo $?`

if [[ ! $state_zero -eq 1 ]]; then
  echo "Incorrect: call without arguments must result in an exit state of 1"
  exit 1
fi

if [[ ! $state_one -eq 0 ]]; then
  echo "Incorrect: call with one valid argument must result in an exit state of 0"
  exit 1
fi

if [[ ! $state_nonsense -eq 1 ]]; then
  echo "Incorrect: call with one nonsense argument must result in an exit state of 1"
  exit 1
fi

if [[ ! $state_one_two -eq 1 ]]; then
  echo "Incorrect: call with two arguments must result in an exit state of 1"
  exit 1
fi

#####################
# Test output
#####################

# Create expected result
echo "false" > expected_0.txt
echo "false" > expected_1.txt
echo "true"  > expected_2.txt
echo "true"  > expected_3.txt
echo "false" > expected_4.txt
echo "true"  > expected_5.txt

# Create the actual result
./main 0 > created_0.txt
./main 1 > created_1.txt
./main 2 > created_2.txt
./main 3 > created_3.txt
./main 4 > created_4.txt
./main 5 > created_5.txt

# Compare results
if ! cmp --silent created_0.txt expected_0.txt; then
  echo "Incorrect: call with 0 does not give correct result"
  exit 1
fi

if ! cmp --silent created_1.txt expected_1.txt; then
  echo "Incorrect: call with 1 does not give correct result"
  exit 1
fi

if ! cmp --silent created_2.txt expected_2.txt; then
  echo "Incorrect: call with 2 does not give correct result"
  exit 1
fi

if ! cmp --silent created_3.txt expected_3.txt; then
  echo "Incorrect: call with 3 does not give correct result"
  exit 1
fi

if ! cmp --silent created_4.txt expected_4.txt; then
  echo "Incorrect: call with 4 does not give correct result"
  exit 1
fi

if ! cmp --silent created_5.txt expected_5.txt; then
  echo "Incorrect: call with 5 does not give correct result"
  exit 1
fi

rm expected_*.txt
rm created_*.txt

#####################
# Test misc
#####################

# Avoid endls
n=`cat main.cpp | egrep "endl" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: C++ Core Guidelines: SL.io.50: Avoid endl"
  exit 1
fi

# Catch exceptions by reference
n=`cat main.cpp | egrep "invalid_argument\s*\w*\s*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: C++ Core Guidelines: E.15: Catch exceptions from a hierarchy by reference"
  exit 1
fi

n=`cat main.cpp | egrep "out_of_range\s*\w*\s*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: C++ Core Guidelines: E.15: Catch exceptions from a hierarchy by reference"
  exit 1
fi

n=`cat main.cpp | egrep "exception\s*\w*\s*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: C++ Core Guidelines: E.15: Catch exceptions from a hierarchy by reference"
  exit 1
fi

# Exceptions should be const
n=`cat main.cpp | egrep "\(\w*(std::)?invalid_argument" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: C++ Core Guidelines: Con.4: Use const to define objects with values that do not change after construction"
  exit 1
fi

n=`cat main.cpp | egrep "\(\w*(std::)?out_of_range" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: C++ Core Guidelines: Con.4: Use const to define objects with values that do not change after construction"
  exit 1
fi

n=`cat main.cpp | egrep "\(\w*(std::)?exception" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: C++ Core Guidelines: Con.4: Use const to define objects with values that do not change after construction"
  exit 1
fi

# Do not use ellipsis
n=`cat main.cpp | egrep "\(\w*\.\.\.\w*\)" | wc -l`
if [ ! "$n" -eq "0" ]; then
  echo "Error: do not use ellipsis"
  exit 1
fi

##########################################
# Test debug version
##########################################
make debug
./main

#####################
# Test code coverage
#####################

n=`gcov-7 -i -n -o debug main.cpp| head -n 2 | tail -n 1 | egrep "100\.00\%" | wc -l`
if [ ! "$n" -eq "1" ]; then
  echo "Error: must have 100% code coverage. Current code coverage:"
  gcov-7 -i -n -o debug main.cpp | head -n 2 | tail -n 1
  exit 1
fi

echo "Correct"
