#!/bin/bash

# From https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_doxygen

rm -f main_tmp.cpp
rm -f Doxyfile
rm -f Doxyfile.bak

# Create a file that is read by Doxygen
( echo "/** @file */"; cat main.cpp ) > main_tmp.cpp

# Generate standard Doxyfile
doxygen -g > /dev/null

# Show the undocumented lines
(cat Doxyfile ; echo "EXCLUDE=README.md" ; echo "QUIET = YES") | doxygen - 2>&1 | egrep "warning"

# Count the number of warnings in the STDOUT and STDERR of Doxygen
exit_code=`(cat Doxyfile ; echo "EXCLUDE=README.md" ; echo "QUIET = YES") | doxygen - 2>&1 | egrep "warning" | wc --lines`

if [[ ! $exit_code -eq 0 ]]; then
  echo "Incorrect: incomplete documentation"
  (cat Doxyfile ; echo "EXCLUDE=README.md" ; echo "QUIET = YES") | doxygen -
fi

rm -f main_tmp.cpp
rm -f Doxyfile
rm -f Doxyfile.bak
rm -rf html
rm -rf latex

exit $exit_code