#!/bin/bash

if [ ! -f test ]; then

  echo "This script is only for cleaning a chapter's folder"
  echo "Do not use clean_test in other folders"

  exit 1

fi 

rm -rf html
rm -rf latex
rm -rf debug
rm -rf release
rm -rf check_*

if [[ -f Makefile ]]; then rm Makefile; fi
if [[ -f Makefile.Debug ]]; then rm Makefile.Debug; fi
if [[ -f Makefile.Release ]]; then rm Makefile.Release; fi
rm install
rm do_oclint
if [[ -f main     ]]; then rm main    ; fi
if [[ -f main.cpp ]]; then rm main.cpp; fi
if [[ -f main.pro ]]; then rm main.pro; fi
rm created_*.txt
rm expected_*.txt
rm README.md
rm test_tests
rm install_oclint
rm get_code_cov
rm gmon.out
# Also remove itself
rm clean_test

