#!/bin/bash

my_files=`ls {*.cpp,*.h}`

./oclint-0.10.3/bin/oclint -o oclint.log \
  $my_files \
  -- \
  -c -std=c++11

# Will be 0 if success
# Will be 1 if fail
fail=`egrep "Compiler Errors" oclint.log | wc -l`

if [ $fail -eq 1 ]; 
then
  echo "OCLint: Compiler error, checking by OCLint may be less strict"
  cat oclint.log
  # exit 1 # OCLint be mild
fi

# Will be 1 if success
# Will be 0 if fail
success=`egrep "FilesWithViolations=0 P1=0 P2=0 P3=0" oclint.log | wc -l`

if [ $success -eq 0 ]; 
then
  echo "Incorrect:"
  cat oclint.log
fi