#!/bin/bash

cpp_files=`ls *.cpp`
h_files=`ls *.h`

./oclint-0.10.3/bin/oclint -o oclint.log \
  $cpp_files \
  $h_files \
  -- \
  -c -std=c++17 \
  -I/usr/include/c++/7 \
  -I/usr/include/x86_64-linux-gnu/c++/7

# Will be 0 if success
# Will be 1 if fail
fail=`egrep "Compiler Errors" oclint.log | wc -l`

if [ $fail -eq 1 ]; 
then
  echo "OCLint: Compiler error, checking by OCLint may be less strict"
  cat oclint.log
  # exit 1 # OCLint be mild
fi

# Will be 1 if success
# Will be 0 if fail
success=`egrep "FilesWithViolations=0 P1=0 P2=0 P3=0" oclint.log | wc -l`

if [ $success -eq 0 ]; 
then
  echo "Incorrect:"
  cat oclint.log
fi