#!/bin/bash

# This code is run on each chapter's GitHub

# Codecov
sudo pip install codecov

# OCLint
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/install_oclint
chmod +x install_oclint 
./install_oclint

# cppcheck
sudo apt-get install -qq cppcheck

# Doxygen
sudo apt-get install -qq doxygen graphviz

# OCLint
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/do_oclint
chmod +x do_oclint

# Codecov
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/get_code_cov
chmod +x get_code_cov

# Check guidelines
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/check_cpp_core_guidelines
chmod +x check_cpp_core_guidelines

# Check documentation
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/check_doc
chmod +x check_doc

# Check course guidelines
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/check_course_guidelines
chmod +x check_course_guidelines

# Don't check for main.pro, it will be downloaded by .travis.yml

