#!/bin/bash

# This code is run on each chapter's GitHub

# GCC 5, GCC 7
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -qq

# Codecov
sudo pip install codecov

# OCLint
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/install_oclint
chmod +x install_oclint 
./install_oclint

# GCC5 
sudo apt-get install -qq g++-5
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
# GCC 7
# - sudo apt-get install -qq g++-7
# - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
# - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
# cppcheck

# cppcheck
sudo apt-get install -qq cppcheck

# Doxygen
sudo apt-get install -qq doxygen graphviz

# OCLint
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/do_oclint
chmod +x do_oclint

# Codecov
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/get_code_cov
chmod +x get_code_cov

# Check guidelines
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/check_cpp_core_guidelines
chmod +x check_cpp_core_guidelines

# Check documentation
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/check_doc
chmod +x check_doc

# Check course guidelines
wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/check_course_guidelines
chmod +x check_course_guidelines

if [[ ! -f main.pro ]]; then 
  echo "main.pro absent"
  exit 1 
fi

#  # Use console .pro file as basis, will be overwritten if needed
#  if [[ -f main.pro ]]; then rm main.pro; fi
#  wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/main.pro

#  # Get correct .pro file
#  if [[ `echo $PWD | egrep "_sfml" | wc --lines` > 0 ]] ; 
#  then 
#    echo "SFML detected" 
#
#    # Install SFML libraries
#    sudo apt-get install libsfml-dev
#
#    # main.pro file
#    rm main.pro
#    wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/main_sfml.pro
#    mv main_sfml.pro main.pro
#  fi
