#!/bin/bash

# Tests the test script.

n_errors=0

# Folders starting with 'rejected_' should contain files to be rejected
for foldername in `ls -d -- reject_*/`; do

  rm -f *.cpp; rm -f *.h; rm -f *.ui; rm -f main

  cp $foldername/*.* .
  ./test &> /dev/null
  exit_code=`echo $?`
  if [[ $exit_code -eq 0 ]]; then
    echo "Incorrect: folder with name '"$foldername" ' should fail"
    ((++n_errors))
  fi

  rm -f *.cpp; rm -f *.h; rm -f *.ui; rm -f main

done

# Files starting with 'accepted_' should be rejected
for foldername in `ls -d -- accept_*/`; do

  rm -f *.cpp; rm -f *.h; rm -f *.ui; rm -f main

  cp $foldername/*.* .

  ./test &> /dev/null
  exit_code=`echo $?`
  if [[ ! $exit_code -eq 0 ]]; then
    echo "Incorrect: folder with name '"$foldername" ' should be accepted"
    ./test
    ((++n_errors))
  fi

  rm -f *.cpp; rm -f *.h; rm -f *.ui; rm -f main

done

rm -rf debug
rm -rf release
rm -f gmon.out
rm -f Makefile
rm -f Makefile.Release
rm -f Makefile.Debug
rm -f main
rm -f .qmake.stash
rm -f *.qrc
rm -f TravisCi.png

exit $n_errors
