#!/bin/bash

# Tests the test script.

n_errors=0

# Files starting with 'rejected_' should be rejected
for filename in `ls reject_*.cpp`; do

  # Remove main iff present
  if [[ -f main ]]; then rm main; fi

  cp $filename main.cpp
  ./test &> /dev/null
  exit_code=`echo $?`
  if [[ $exit_code -eq 0 ]]; then
    echo "Incorrect: file with name '"$filename" ' should fail"
    ((++n_errors))
  fi
  rm main.cpp
done

# Files starting with 'accepted_' should be rejected
for filename in `ls accept_*.cpp`; do

  # Remove main iff present
  if [[ -f main ]]; then rm main; fi

  cp $filename main.cpp
  ./test &> /dev/null
  exit_code=`echo $?`
  if [[ ! $exit_code -eq 0 ]]; then
    echo "Incorrect: file with name '"$filename" ' should be accepted"
    ./test
    ((++n_errors))
  fi
  rm main.cpp
done

rm -rf debug
rm -rf release
rm gmon.out
rm Makefile
rm Makefile.Release
rm Makefile.Debug
rm main

exit $n_errors
