#!/bin/bash

# root folder
cd ..
markdown-link-check README.md

# doc
cd doc
find . -name \*.md -exec markdown-link-check {} \; 2>/dev/null | egrep "[✖]"
# find . -name \*.md -exec markdown-link-check {} \;
exit 0
