#!/bin/bash

# Copy the accepted_0.cpp of each chapter to the folder of that chapter, to see if it is indeed accepted

cd ~/GitHubs

for folder in `ls | egrep "correct_cpp_" | egrep -v "video"`; do
  echo $folder
  chapter=`echo $folder | sed 's/correct_cpp_//'`
  cp ~/GitHubs/correct_cpp/chapters/$chapter/reject_0/*.* $folder
done
