#!/bin/bash

# Copy the main.pro files to all Correct C++ chapters

cd ..
cd chapters

for chapter in `ls -d */ | egrep -v "scoreboard"`; do
  echo "chapter: "$chapter
  to="/home/richel/GitHubs/correct_cpp_"$chapter"main.pro"
  echo "to: "$to
  cd $chapter
  cp main.pro $to
  cd ..
done
