#!/bin/bash

# Put all chapters after another and create a booklet

mkdir build
cp ../*.md build
cd build

# Remove chapters from booklet
rm README.md

for filename in `ls *.md` do
  echo $filename
  cat $filename >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
done

# Make book
pandoc README.md -o correct_cpp.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in

# Make booklet
bookletimposer -a correct_cpp_book.pdf -o correct_cpp_booklet.pdf

cp correct_cpp_book.pdf ../
cp correct_cpp_booklet.pdf ../
rm -rf build
