#!/bin/bash

# Put all chapters after another and create a booklet

cd ..

for filename in `ls *.md | egrep -v README | egrep -v CONTRIBUTING | egrep -v LICENSE | egrep -v code_of_conduct.md | egrep -v faq.md`; do
  echo $filename
  cat $filename >> book.md; echo " " >> book.md; echo "\pagebreak" >> book.md; echo " " >> book.md
done

# Make book
pandoc book.md -o correct_cpp.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in

# Make booklet
bookletimposer -a correct_cpp.pdf -o correct_cpp_booklet.pdf

rm book.md
