#!/bin/bash

# Put all chapters after another and create a booklet

cd ../doc

for filename in `ls *.md | egrep -v code_of_conduct.md | egrep -v faq.md`; do
  echo $filename
  cat $filename >> book.md; echo " " >> book.md; echo "\pagebreak" >> book.md; echo " " >> book.md
done

# Convert text of book
pandoc book.md -o text.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in

# Prepend title page
pdfunite ../scripts/title.pdf text.pdf correct_cpp.pdf

# Make booklet
bookletimposer -a correct_cpp.pdf -o correct_cpp_booklet.pdf

rm book.md
rm text.pdf

mv correct_cpp.pdf ../
mv correct_cpp_booklet.pdf ../
